### ISSUE TITLE
Mismatch in number of sequences

### ISSUE THREAD

**Issue by emalgorithm** [Rfam/rfam-docs#26]
Hi,

The [page](http://rfam.xfam.org/family/RF00014#tabview=tab1) for the sequences of family RF00014 says there are 40 sequences for that family. However, when downloading the file with the aligned sequences (FASTA), I can only count 38 distinct sequences. Am I missing something?

Best,
Emanuele

**Comment by kalvari** [comment]
Hi Emanuele,

Thank you for reporting this. You are right! The number of significant sequences is **40**, but there are only 39 sequences in the FASTA file. I will look into it and try to get it fixed the soonest possible. 

Kind regards,
Ioanna

**Comment by emalgorithm** [comment]
Another quick question. I noticed that the RNA sequences in the database contain the 'T' base as opposed to 'U'. Is this just for simplicity or is there some reason?

Thanks,
Emanuele

**Comment by kalvari** [comment]
Dear Emanuele,

Our sequence database is composed of a collection of non-redundant complete genomes that we annotate with non-coding RNAs using our covariance models. We extract the sequences in the fasta files directly from those genome assemblies, hence the Ts. You can get the exact ncRNA sequence by replacing the Ts with Us. To cross check this you can use RNAcentral [sequence search](https://rnacentral.org/sequence-search/) and search for one of the sequences in `RF00014`.  

I would also like to inform you that the fasta files have now been fixed and are available on the [FTP](http://ftp.ebi.ac.uk/pub/databases/Rfam/CURRENT/) 

Please feel free to let me know if you have any other questions.

Kind regards,
Ioanna

**Comment by AntonPetrov** [comment]
Closing this issue - please feel free to reopen if the problem persists.
