### ISSUE TITLE
Sequence Search unavailable

### ISSUE THREAD

**Issue by SarahJD3** [Rfam/rfam-docs#41]
The sequence search states temporarily unavailable, but it has been a while. Is there an estimate of when it will be up and running again?

**Comment by blakesweeney** [comment]
Hi, the sequence search is currently down, we are working to get it back up and hope to have it working again within a day. Our apologies for the issue and any troubles caused.

**Comment by SarahJD3** [comment]
Hi, thank you so much for the update!
