### ISSUE TITLE
writing a mysql query

### ISSUE THREAD

**Issue by Anu-Ra-g** [Rfam/rfam-docs#48]
In the family table, I want to paginate a list of the family names and their longest DNA sequence lengths (in descending order of length) where only families that have DNA sequence lengths greater than 1,000,000 are included. Give a query that will return the 9th page when there are 15 results per page. (hint: we need the family accession ID, family name, and the maximum length in the results)

What are the necessary columns? I can't figure it out.

**Comment by blakesweeney** [comment]
Hi, thanks for reaching out to Rfam. I'd be happy to help you with this request. Could you let me know what you've tried and why you need this data? Maybe there is an easier way to get it. Thanks!

**Comment by Anu-Ra-g** [comment]
This is for the purpose of an assignment. Here is the question:-
Paginate a list of the family names and their longest DNA sequence lengths (in descending order of length) where only families that have DNA sequence lengths greater than 1,000,000 are included. Give a query that will return the 9th page when there are 15 results per page. 
(hint: we need the family accession ID, family name, and the maximum length in the results)
I couldn't figure out the columns in the family table.

**Comment by blakesweeney** [comment]
I suggest you look a bit at the family table. The first entry starts with:

```
RF00001	5S_rRNA	1302	5S ribosomal RNA	
```

I suspect your teacher is interested in the first two columns. Good luck with your assignment!
