### ISSUE TITLE
Can't download alignment

### ISSUE THREAD

**Issue by klausindc** [Rfam/rfam-docs#50]
Hi,
I am trying to look at U4 (RF00015) and download an alignment from Species-Tree that I have selected. However, it states 'There was a problem collecting sequence accessions'

Anyway around this?

Thanks,
Klaus
![image](https://github.com/Rfam/rfam-docs/assets/11062471/db3c4ab1-2483-45e5-a882-c90146c81e8d)

**Comment by nancyontiveros** [comment]
Dear Klaus,

I'm sorry for the late replay

[RF00015.nhx.txt](https://github.com/Rfam/rfam-docs/files/14916621/RF00015.nhx.txt)

I hope the attached alignment is what you need

Nancy Ontiveros

**Comment by klausindc** [comment]
Thanks, I was planning to compare several different alignments and I am also probably a newbie since it is not clear to me how to use the alignment you sent (but thank you for doing it). Is the site not working as it should so that I can use the tools directly myself?

All the best,
Klaus
